doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            Article:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Blog/Article/Infrastructure/DoctrineMapping'
                prefix: 'App\Blog\Article\Domain\Entity'
                alias: Article
            Category:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Blog/Category/Infrastructure/DoctrineMapping'
                prefix: 'App\Blog\Category\Domain\Entity'
                alias: Category
            User:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Authentication/User/Infrastructure/DoctrineMapping'
                prefix: 'App\Authentication\User\Domain\Entity'
                alias: User
            ApiToken:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Authentication/ApiToken/Infrastructure/DoctrineMapping'
                prefix: 'App\Authentication\ApiToken\Domain\Entity'
                alias: ApiToken
            Game:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Competition/Profile/Game/Infrastructure/DoctrineMapping'
                prefix: 'App\Competition\Profile\Game\Domain\Entity'
                alias: Game
            Player:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Competition/Profile/Player/Infrastructure/DoctrineMapping'
                prefix: 'App\Competition\Profile\Player\Domain\Entity'
                alias: Player
            Team:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Competition/Profile/Team/Infrastructure/DoctrineMapping'
                prefix: 'App\Competition\Profile\Team\Domain\Entity'
                alias: Team
            Competitor:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Competition/Competitor/Infrastructure/DoctrineMapping'
                prefix: 'App\Competition\Competitor\Domain\Entity'
                alias: Competitor
            Fight:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Competition/Fight/Infrastructure/DoctrineMapping'
                prefix: 'App\Competition\Fight\Domain\Entity'
                alias: Fight
            Clan:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Competition/Profile/Clan/Infrastructure/DoctrineMapping'
                prefix: 'App\Competition\Profile\Clan\Domain\Entity'
                alias: Clan
            Tournament:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Competition/Tournament/Infrastructure/DoctrineMapping'
                prefix: 'App\Competition\Tournament\Domain\Entity'
                alias: Tournament
            Ranking:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Competition/Ranking/Infrastructure/DoctrineMapping'
                prefix: 'App\Competition\Ranking\Domain\Entity'
                alias: Ranking

        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
