security:
    password_hashers:
        App\Authentication\User\Domain\Entity\User: 'auto'

    providers:
        app_user_provider:
            id: App\Authentication\User\Infrastructure\Security\UserProvider

    role_hierarchy:
        ROLE_ADMIN: [ROLE_EDITOR]
        ROLE_EDITOR: [ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            user_checker: App\Authentication\User\Infrastructure\Security\UserChecker
            json_login:
                check_path: api_login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        bot:
            pattern: ^/api/bot
            stateless: true
            access_token:
                token_handler: App\Authentication\ApiToken\Infrastructure\Security\ApiTokenHandler
                failure_handler: App\Authentication\ApiToken\Infrastructure\Security\ApiTokenEntryPoint
            entry_point: App\Authentication\ApiToken\Infrastructure\Security\ApiTokenEntryPoint

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            user_checker: App\Authentication\User\Infrastructure\Security\UserChecker
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/bot, roles: ROLE_BOT }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/editor, roles: ROLE_EDITOR }
        - { path: ^/api/user, roles: ROLE_USER }
        - { path: ^/api/(login|register)$, methods: [POST], roles: PUBLIC_ACCESS }
        - { path: ^/api, methods: [GET, HEAD], roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_NO_ACCESS }

when@test:
    security:
        password_hashers:
            App\Authentication\User\Domain\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
