/* eslint-disable */
/**
 * Auto-generated by `npm run api:types` from https://localhost/api/doc.json.
 * Do not edit by hand — re-run the script instead.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_user_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verify-email/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_verify_email"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_comment_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_article"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_article_list"];
        put?: never;
        post: operations["post_api_article_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_comment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_category_list"];
        put?: never;
        post: operations["post_api_category_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fights/{id}/results/{gameid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_fight_results"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/pending/players/{gameid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_results_pending_players"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/users/fights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_results_pending_user_fights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fights/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_api_fight_results_patch"];
        trace?: never;
    };
    "/api/fights/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_fight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fights/results/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_fight_results_confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_game_list"];
        put?: never;
        post: operations["post_api_game_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_player"];
        put?: never;
        post?: never;
        delete: operations["delete_api_player_delete"];
        options?: never;
        head?: never;
        patch: operations["patch_api_player_patch"];
        trace?: never;
    };
    "/api/players/{id}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_player_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_player_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_team_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable reason for the failure */
            error?: string;
        };
        /** @description An identifier, serialized as a value object */
        Uuid: {
            /** Format: uuid */
            value?: string;
        };
        /** @description A blog article. `author` names the user who published it and `category` the category it is filed under. Its comments are not part of it. */
        Article: {
            category?: components["schemas"]["Uuid"];
            id?: components["schemas"]["Uuid"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            body?: string;
            title?: string;
            author?: components["schemas"]["Uuid"];
        };
        /** @description A comment on an article. */
        Comment: {
            id?: components["schemas"]["Uuid"];
            message?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            articleId?: components["schemas"]["Uuid"];
        };
        /** @description A blog category. Unlike other resources, its id is a plain string, not a value object. */
        Category: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
        };
        /** @description The authenticated user, with the player profiles they hold. Unlike other resources, identifiers here are plain strings, not value objects. */
        CurrentUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            username: string;
            roles: string[];
            verified: boolean;
            /** @description One entry per game the user holds a player profile in, oldest first. Empty when they hold none. */
            players: {
                /** Format: uuid */
                id: string;
                /** @example PlayerOne#1234 */
                battletag: string;
                /**
                 * Format: uuid
                 * @description Game ID
                 */
                game: string;
            }[];
        };
        /** @description A game players can register in */
        Game: {
            id?: components["schemas"]["Uuid"];
            title?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description One user in one game. `user` names the account, `game` the game. */
        Player: {
            id?: components["schemas"]["Uuid"];
            battletag?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            game?: components["schemas"]["Uuid"];
            user?: components["schemas"]["Uuid"];
        };
        /** @description A fight between two competitors, in the order it holds them */
        Fight: {
            id?: components["schemas"]["Uuid"];
            competitorOne?: components["schemas"]["Uuid"];
            competitorTwo?: components["schemas"]["Uuid"];
            /** @description The competitor that declared the outcome. Null while nothing has been declared. */
            declaredBy?: {
                /** Format: uuid */
                value?: string;
            } | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description What one side of a fight scored, and where that claim stands */
        Result: {
            id?: components["schemas"]["Uuid"];
            fight?: components["schemas"]["Uuid"];
            competitor?: components["schemas"]["Uuid"];
            /**
             * @description Points this side scored. Zero until a declaration carries a real value.
             * @example 3
             */
            score?: number;
            /**
             * @description `pending` while nobody declared anything, `reporting` while one side waits for the other to confirm, then the settled outcome.
             * @enum {string}
             */
            status?: "pending" | "reporting" | "win" | "loss" | "draw";
            /**
             * @description The outcome the declaring side claims. Carried only while `status` is `reporting`.
             * @enum {string|null}
             */
            reportedStatus?: "win" | "loss" | "draw" | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description A player profile as a list names it: its id and the battletag it goes by. */
        PlayerProfile: {
            id?: components["schemas"]["Uuid"];
            /**
             * @description How this profile is named in its game.
             * @example PlayerOne#1234
             */
            battletag?: string | null;
        };
        /** @description One side of a fight: the competitor, the player profile behind it, and what that side claims. */
        FightSide: {
            competitor?: components["schemas"]["Uuid"];
            /** @description The player profile this competitor stands for. Null for a team, and for a profile that no longer exists. */
            player?: {
                /** Format: uuid */
                value?: string;
            } | null;
            /**
             * @description How this side is named in the game. Null whenever `player` is.
             * @example PlayerOne#1234
             */
            battletag?: string | null;
            /**
             * @description Points this side scored. Zero until a declaration carries a real value.
             * @example 3
             */
            score?: number;
            /**
             * @description Where this side stands, as `GET /api/fights/{id}/results/{gameid}` reports it.
             * @enum {string}
             */
            status?: "pending" | "reporting" | "win" | "loss" | "draw";
            /**
             * @description The outcome the declaring side claims. Carried only while `status` is `reporting`.
             * @enum {string|null}
             */
            reportedStatus?: "win" | "loss" | "draw" | null;
        };
        /** @description A fight as a list shows it: the fight, where it stands as a whole, and its two sides named by battletag. */
        FightSummary: {
            id?: components["schemas"]["Uuid"];
            competitorOne?: components["schemas"]["Uuid"];
            competitorTwo?: components["schemas"]["Uuid"];
            /** @description The competitor that declared the outcome. Null while nothing has been declared. */
            declaredBy?: {
                /** Format: uuid */
                value?: string;
            } | null;
            /** @description The game both sides are registered in, read from their profiles. Null when neither side resolves to a player. */
            game?: {
                /** Format: uuid */
                value?: string;
            } | null;
            /**
             * @description `pending` while nobody declared anything, `reporting` while a declaration waits for its confirmation, `finished` once both sides are settled.
             * @enum {string}
             */
            status?: "pending" | "reporting" | "finished";
            /** @description Both sides, in the order the fight holds them. */
            sides?: components["schemas"]["FightSide"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: {
        /** @description Invalid input: a value object rule or a business rule was violated */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, expired or revoked JWT */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example 401 */
                    code?: number;
                    /** @example JWT Token not found */
                    message?: string;
                };
            };
        };
        /** @description The user is known but lacks the required role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A resource referenced by the request does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_user_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user, and the player profiles they hold: one per game at most, oldest first. `players` is an empty array when they hold none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    get_api_verify_email: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        /** Format: email */
                        email?: string;
                        username?: string;
                        roles?: string[];
                        /** @example true */
                        verified?: boolean;
                    };
                };
            };
            /** @description Token is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    post_api_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The account username.
                     * @example john_doe
                     */
                    username: string;
                    /**
                     * Format: password
                     * @example Password123!
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token?: string;
                    };
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example logged out */
                        message?: string;
                    };
                };
            };
            /** @description No JWT sent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /** @example john_doe */
                    username: string;
                    /**
                     * Format: password
                     * @example Password123!
                     */
                    password: string;
                    /**
                     * Format: password
                     * @example Password123!
                     */
                    passwordConfirmation: string;
                    /**
                     * @description Language of the verification email.
                     * @example fr
                     * @enum {string}
                     */
                    locale: "fr" | "en";
                };
            };
        };
        responses: {
            /** @description User registered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        /** Format: email */
                        email?: string;
                        username?: string;
                        roles?: string[];
                        /** @example false */
                        verified?: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    get_api_comment_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every comment on the article, oldest first. An empty array when nobody has commented yet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    get_api_article: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article found, including its comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        category?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        id?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        /** Format: date-time */
                        createdAt?: string;
                        /** Format: date-time */
                        updatedAt?: string;
                        body?: string | null;
                        title?: string | null;
                        author?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        comments?: {
                            id?: {
                                /** Format: uuid */
                                value?: string;
                            };
                            message?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                            articleId?: {
                                /** Format: uuid */
                                value?: string;
                            };
                        }[];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    get_api_article_list: {
        parameters: {
            query?: {
                /** @description Which page to read, 1 by default. */
                page?: number;
                /** @description How many articles that page holds, 10 by default and 50 at most. */
                limit?: number;
                /** @description Keeps the articles whose title or body contains this text, whatever the case. A blank value is no search. */
                q?: string;
                /** @description Keeps the articles filed under this category, named by its slug. */
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of articles, newest first. Comments are not included: `GET /api/articles/{id}` returns an article with its comments. `items` is empty when the filters match nothing, or when the page is past the last one. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Article"][];
                        /**
                         * @description Articles the filters match, every page taken together
                         * @example 42
                         */
                        total: number;
                        /**
                         * @description The page these items come from
                         * @example 1
                         */
                        page: number;
                        /**
                         * @description How many items a full page holds
                         * @example 10
                         */
                        limit: number;
                        /**
                         * @description How many pages the filters yield, 0 when nothing matches
                         * @example 5
                         */
                        pages: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description No category has the requested slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_article_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example My article */
                    title: string;
                    /** @example Article content... */
                    body: string;
                    /**
                     * @description Slug of an existing category
                     * @example news
                     */
                    categorySlug: string;
                };
            };
        };
        responses: {
            /** @description Article created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Category ID (resolved from categorySlug) */
                        category?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        id?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        /** Format: date-time */
                        createdAt?: string;
                        /** Format: date-time */
                        updatedAt?: string;
                        body?: string | null;
                        title?: string | null;
                        author?: {
                            /** Format: uuid */
                            value?: string;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    post_api_comment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description ID of the commented article
                     */
                    articleId: string;
                    /** @example Great article! */
                    message: string;
                };
            };
        };
        responses: {
            /** @description Comment created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        message?: string;
                        /** Format: date-time */
                        createdAt?: string;
                        /** Format: date-time */
                        updatedAt?: string;
                        articleId?: {
                            /** Format: uuid */
                            value?: string;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    get_api_category_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every category, by name. Public: the blog filters its articles by category. An empty array when no category has been created yet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    post_api_category_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example News */
                    name: string;
                    /** @example news */
                    slug: string;
                };
            };
        };
        responses: {
            /** @description Category created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        name?: string;
                        slug?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    get_api_fight_results: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fight ID */
                id: string;
                /** @description Game the fight is played in. Together with the authenticated user it names which of the two sides is asking. */
                gameid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's own result in this fight. While it is `reporting`, `score` and `reportedStatus` hold what the declaring side claims — prefill the confirmation form with them. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The game, the fight, or a result for the caller in it, does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_results_pending_players: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game to read. The results returned are those of the player profile the authenticated user holds in it. */
                gameid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The unsettled results of the player profile the authenticated user owns in this game, oldest first: `pending` while nobody declared, `reporting` while one side waits for the other to confirm. An empty array when nothing is waiting. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The authenticated user holds no player profile competing in this game */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_results_pending_user_fights: {
        parameters: {
            query?: {
                /** @description Which page to read, 1 by default. */
                page?: number;
                /** @description How many results that page holds, 10 by default and 50 at most. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the unsettled results of every competitor profile the authenticated user owns, whatever the game, oldest first: `pending` while nobody declared, `reporting` while one side waits for the other to confirm. Each item carries the caller's own side, the game it is played in, and the other side. `items` is empty when nothing is waiting, when the page is past the last one, and when the caller holds no player profile at all. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: (components["schemas"]["Result"] & {
                            /** @description The game the caller's profile is registered in. Null when that profile no longer exists. */
                            game?: {
                                /** Format: uuid */
                                value?: string;
                            } | null;
                            /** @description The caller's own player profile, the one this result belongs to. */
                            player?: components["schemas"]["PlayerProfile"] | null;
                            /** @description The other side of the fight. `player` is null for a team, and for a profile that no longer exists. */
                            opponent?: {
                                competitor?: {
                                    /** Format: uuid */
                                    value?: string;
                                };
                                player?: components["schemas"]["PlayerProfile"] | null;
                            } | null;
                        })[];
                        /**
                         * @description Unsettled results the caller has, every page taken together
                         * @example 42
                         */
                        total: number;
                        /**
                         * @description The page these items come from
                         * @example 1
                         */
                        page: number;
                        /**
                         * @description How many items a full page holds
                         * @example 10
                         */
                        limit: number;
                        /**
                         * @description How many pages the caller has, 0 when nothing is waiting
                         * @example 5
                         */
                        pages: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    patch_api_fight_results_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fight ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description The outcome for each side, in the order the fight holds its competitors — `GET /api/fights/{id}/results/{gameid}` returns them in that same order. The two statuses must agree: a win against a loss, or two draws. The declaring side is the authenticated user, never a field of the body. */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Fight being declared. Repeat the `id` of the path here.
                     */
                    fight: string;
                    /**
                     * Format: uuid
                     * @description Game of the fight: with the authenticated user it names the competitor declaring the results
                     */
                    game: string;
                    /**
                     * @description Outcome claimed for the first competitor of the fight
                     * @enum {string}
                     */
                    competitorOneStatus: "win" | "loss" | "draw";
                    /** @example 3 */
                    competitorOneScore: number;
                    /**
                     * @description Outcome claimed for the second competitor of the fight
                     * @enum {string}
                     */
                    competitorTwoStatus: "win" | "loss" | "draw";
                    /** @example 1 */
                    competitorTwoScore: number;
                };
            };
        };
        responses: {
            /** @description Results declared, waiting for the other side to confirm them. Both results move to `reporting`, carrying the claimed score in `score` and the claimed outcome in `reportedStatus`. The fight is returned, with `declaredBy` naming the side that just declared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fight"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The fight, or a result for one of its two sides, does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_fight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description ID of the first player
                     */
                    playerOne: string;
                    /**
                     * Format: uuid
                     * @description ID of the second player
                     */
                    playerTwo: string;
                };
            };
        };
        responses: {
            /** @description Fight created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        competitorOne?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        competitorTwo?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        /** Format: date-time */
                        createdAt?: string;
                        /** Format: date-time */
                        updatedAt?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    post_api_fight_results_confirmation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Names the fight to settle. Confirming means agreeing with the results exactly as they were declared, so read them with `GET /api/fights/{id}/results/{gameid}` first. A side that disagrees does not confirm, and settles it with an admin. */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Fight whose declared results are being confirmed
                     */
                    fight: string;
                    /**
                     * Format: uuid
                     * @description Game of the fight: with the authenticated user it names the competitor confirming the results
                     */
                    game: string;
                };
            };
        };
        responses: {
            /** @description Both results are settled, each carrying its final `status` and `score`. The fight is returned, with `declaredBy` still naming the side that had declared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fight"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The fight, or a result for one of its two sides, does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_game_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every game, by title. An empty array when no game has been created yet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
        };
    };
    post_api_game_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Requires a user with the administrator role (checked at the application layer) */
        requestBody: {
            content: {
                "application/json": {
                    /** @example Street Fighter 6 */
                    title: string;
                };
            };
        };
        responses: {
            /** @description Game created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        title?: string | null;
                        /** Format: date-time */
                        createdAt?: string;
                        /** Format: date-time */
                        updatedAt?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    get_api_player: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Player ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One player profile: who they are in the game they registered in. Public, so that a visitor can read a profile before deciding to challenge it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    delete_api_player_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Player ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile deleted. It is returned one last time, as it stood. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The profile belongs to another account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No player profile has this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The profile takes part in fights: deleting it would leave that history hanging */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_api_player_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Player ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description The battletag this profile is known by. The game it belongs to never changes: a profile is one account in one game, and the fights already opened for it point at that pair. */
        requestBody: {
            content: {
                "application/json": {
                    /** @example PlayerOne#1234 */
                    battletag: string;
                };
            };
        };
        responses: {
            /** @description Battletag updated. The profile is returned as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The profile belongs to another account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No player profile has this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_player_list: {
        parameters: {
            query?: {
                /** @description Which page to read, 1 by default. */
                page?: number;
                /** @description How many players that page holds, 10 by default and 50 at most. */
                limit?: number;
                /** @description Keeps the players whose battletag contains this text, whatever the case. A blank value is no search. */
                q?: string;
            };
            header?: never;
            path: {
                /** @description Game ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the players registered in this game, oldest profile first. `items` is empty when the game has no player, when the search matches none, when the page is past the last one, and when no game has this id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Player"][];
                        /**
                         * @description Players the filters match, every page taken together
                         * @example 42
                         */
                        total: number;
                        /**
                         * @description The page these items come from
                         * @example 1
                         */
                        page: number;
                        /**
                         * @description How many items a full page holds
                         * @example 10
                         */
                        limit: number;
                        /**
                         * @description How many pages the filters yield, 0 when nothing matches
                         * @example 5
                         */
                        pages: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    post_api_player_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example PlayerOne#1234 */
                    battletag: string;
                    /**
                     * Format: uuid
                     * @description Game ID
                     */
                    game: string;
                };
            };
        };
        responses: {
            /** @description Player created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        battletag?: string | null;
                        /** Format: date-time */
                        createdAt?: string;
                        /** Format: date-time */
                        updatedAt?: string;
                        game?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        user?: {
                            /** Format: uuid */
                            value?: string;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    post_api_team_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Falcons */
                    name: string;
                    /**
                     * Format: uuid
                     * @description ID of the player added to the team
                     */
                    player: string;
                    /**
                     * Format: uuid
                     * @description ID of the player designated as team captain
                     */
                    leader: string;
                };
            };
        };
        responses: {
            /** @description Team created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: {
                            /** Format: uuid */
                            value?: string;
                        };
                        /** @example Falcons */
                        name?: string | null;
                        /** Format: date-time */
                        createdAt?: string;
                        /** Format: date-time */
                        updatedAt?: string;
                        leader?: {
                            /** Format: uuid */
                            value?: string;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
